name: gcp_secret_manager
description: A small package to make interacting with Google Secret Manager easier.
version: 0.1.2
homepage: https://github.com/Morel-Tech/gcp_secret_manager

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  current_gcp_project: # 0.0.1
    git:
      url: https://github.com/testuser1109/current_gcp_project.git
      ref: main

  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.2
